### ISSUE TITLE
搜图谱说未找到

### ISSUE THREAD

**Issue by w1945512171** [whiterasbk/MiraiQueryPokemon#1]
![QZX6QU~{`W7L_%E(CG`YY 9](https://user-images.githubusercontent.com/111542766/185725989-798857b6-d4ba-4c77-a2d8-cb092f4171d5.png)

**Comment by whiterasbk** [comment]
@w1945512171 是否将 release 下的 query-script.zip 下载解压放到指定位置?

**Comment by w1945512171** [comment]
![Z(_2KI9 $A{LVQH3IYAPBRT](https://user-images.githubusercontent.com/111542766/185726595-d2fce305-4fd6-4256-9bb3-f281904df2c6.png)

**Comment by whiterasbk** [comment]
@w1945512171 多了一层目录，query-script.zip 文件的内容应该在 data/bot.good.QueryPokemon/目录下，将 query-script 文件夹内的东西移出来并删掉 query-script 文件夹就好

**Comment by whiterasbk** [comment]
@w1945512171 多了一层目录，query-script.zip 文件的内容应该在 data/bot.good.QueryPokemon/目录下，将 query-script 文件夹内的东西移出来就好

**Comment by w1945512171** [comment]
okok，谢谢了
